# Generated by Django 5.1.7 on 2025-03-18 21:16

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emplacement_actuel', models.CharField(max_length=255)),
                ('lieu_prise_en_charge', models.CharField(max_length=255)),
                ('lieu_depot', models.CharField(max_length=255)),
                ('cycle_actuel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='JournalELD',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_debut', models.DateTimeField()),
                ('heure_fin', models.DateTimeField()),
                ('duree_pause', models.IntegerField()),
                ('trajet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traject.trajet')),
            ],
        ),
    ]
