# Generated by Django 5.1.7 on 2025-03-19 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journaleld',
            name='heures_conduite',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trajet',
            name='distance_parcourue',
            field=models.FloatField(default=0),
        ),
    ]
