# Generated by Django 5.1.7 on 2025-03-19 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traject', '0002_journaleld_heures_conduite_trajet_distance_parcourue'),
    ]

    operations = [
        migrations.AddField(
            model_name='journaleld',
            name='pause_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journaleld',
            name='duree_pause',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='journaleld',
            name='heure_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
