# Generated by Django 5.1.7 on 2025-03-20 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traject', '0003_journaleld_pause_start_alter_journaleld_duree_pause_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journaleld',
            name='duree_pause',
        ),
        migrations.RemoveField(
            model_name='journaleld',
            name='pause_start',
        ),
        migrations.AddField(
            model_name='journaleld',
            name='offduty_duration',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='journaleld',
            name='offduty_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journaleld',
            name='offduty_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journaleld',
            name='onduty_duration',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='journaleld',
            name='onduty_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journaleld',
            name='onduty_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journaleld',
            name='sleep_duration',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='journaleld',
            name='sleep_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journaleld',
            name='sleep_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
