# Generated by Django 5.1.7 on 2025-03-20 22:59

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traject', '0004_remove_journaleld_duree_pause_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('current_cycle', models.IntegerField()),
                ('distance_traveled', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ELDLog',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('driving_hours', models.FloatField(default=0)),
                ('sleep_start', models.DateTimeField(blank=True, null=True)),
                ('sleep_end', models.DateTimeField(blank=True, null=True)),
                ('sleep_duration', models.FloatField(default=0)),
                ('onduty_start', models.DateTimeField(blank=True, null=True)),
                ('onduty_end', models.DateTimeField(blank=True, null=True)),
                ('onduty_duration', models.FloatField(default=0)),
                ('offduty_start', models.DateTimeField(blank=True, null=True)),
                ('offduty_end', models.DateTimeField(blank=True, null=True)),
                ('offduty_duration', models.FloatField(default=0)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traject.trip')),
            ],
        ),
        migrations.DeleteModel(
            name='JournalELD',
        ),
        migrations.DeleteModel(
            name='Trajet',
        ),
    ]
